server:
  servlet:
    context-path: /auth
  port: 63070
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_education_users?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: root

weixin:
  appid: wx17655f8047b85150
  secret: 68918d65287802a19b1905cbda7eaa93