spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/online_education_learning?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: root