spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhoast:3306/online_education_media?serverTimezone=UTC&userUnicode=true&useSSL=false
    username: root
    password: root
  # 配置本地优先
  cloud:
   config:
    override-none: true
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucket:
    files: mediafiles
    videofiles: video
xxl:
  job:
    admin: 
      addresses: http://localhost:8080/xxl-job-admin
    executor:
      appname: media-process-service
      address: 
      ip: 
      port: 9999
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
    accessToken: default_token
videoprocess:
 ffmpegpath: D:/environment/ffmpeg/ffmpeg.exe



